/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Solvers_IpOptSolvers */

#ifndef _Included_Solvers_IpOptSolvers
#define _Included_Solvers_IpOptSolvers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Solvers_IpOptSolvers
 * Method:    CplSimplex
 * Signature: ([F[F[F[F[F[FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_Solvers_IpOptSolvers_CplSimplex
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jint);

/*
 * Class:     Solvers_IpOptSolvers
 * Method:    IpOptFreeSolver
 * Signature: ([F[F[F[F[FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_Solvers_IpOptSolvers_IpOptFreeSolver
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jint);

/*
 * Class:     Solvers_IpOptSolvers
 * Method:    IpOptSingleSolver
 * Signature: ([F[F[F[F[FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_Solvers_IpOptSolvers_IpOptSingleSolver
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
